version: "3.9"

services:
  web:                   # ← everything that belongs to *this* service
    build: .
    container_name: debonair
    env_file: .env
    restart: unless-stopped
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tls:/etc/ssl/private:ro
    ports:           
      - "80:80"
      - "443:443"